routes/web.php
<?php

Route::get('/', function () {
    return redirect('login');
});

//Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/convenios', 'HomeController@convenios');

Route::get('/videos', 'HomeController@videos');

Route::get('/usuarios', 'HomeController@usuarios');

Route::get('/ventas', 'HomeController@ventas');

Route::get('/suscrpciones', 'HomeController@subscription');

Route::get('/subscriptionselect', 'SubscriptionController@subscriptionselect');

Route::resource('/posts','PostController');

Route::resource('/sales','SaleController');

Route::resource('/vistas','ViewsController');

Route::resource('/users','UserController');

Route::resource('/subscription','SubscriptionController');

Route::get('/userlogout', 'HomeController@logout');

Route::get('/goFlow', 'SaleController@goFlow');

Route::get('/perfil', 'HomeController@profile');

Route::get('/changeSub/{id}', 'SubscriptionController@changeSub');

Route::get('/getVideosMonth/{month}', 'PostController@getVideosMonth');

Route::post('/flowConfirm', 'SaleController@flowConfirm');

Route::post('/flowResult', 'SaleController@flowResult');


Route::get('user_list_excel', 'UserController@exportExcel')->name('users.excel');

Route::get('/user/sendmail/{id}', 'SendMailController@userShow');

Route::post('/user/mailsend/{id}', 'SendMailController@mailSend');

Route::post('/usersChangePassword/{id}', 'UserController@passchange');

Route::get('/user/newVideoMail', 'SendMailController@videoMail');

Route::get('/sendMailInactive' , 'SendMailController@sendMailInactive');

Route::get('/emails' , 'SendMailController@index');

Route::get('/emails/{id}' , 'SendMailController@edit');

Route::put('/emails/{id}' , 'SendMailController@update');

app/Email.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Email extends Model
{

    protected $fillable = ['subject', 'body', 'type'];

    const TYPE = [
        1=>'Video Nuevo',
        2=>'Suscripcion Vencida'
    ];
    

    public function getTypeLabelAttribute()
    {
        return Self::TYPE[$this->type];
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Carbon\Carbon;
use App\Sale;
use App\Notifications\UserResetPassword;

class User extends Authenticatable 
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'f_name', 'l_name', 'rut', 'phone', 'address', 'gender', 'region_id', 'provincia_id', 'subscription_id', 'type', 'status',  'email', 'password','last_login_at', 'last_login_ip', 'city', 'imagen'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    const TYPES = array(
        1 => 'Administrador',
        2 => 'Usuario'
    );
    const STATUS = array(
        1 => 'Pendiente',
        2 => 'Activo',
        3 => 'Cancelado',
        4 => 'Renovacion'
    );

    public function region()
    {
        return $this->hasOne('App\Region');
    }
    
    public function provincia()
    {
        return $this->hasOne('App\Provincia');
    }

    public function subscription()
    {
        return $this->belongsTo('App\Subscription');
    }

    public function sales()
    {
        return $this->hasMany('App\Sale');
    }
    
    public function views()
    {
        return $this->hasMany('App\Views');
    }

    public function getFullNameAttribute()
    {
        return "{$this->f_name} {$this->l_name}";
    }

    public function getAgeAttribute()
    {

        return Carbon::parse($this->birthday_at)->age;
    }
    
    public function getMonthviewsAttribute()
    {
        $now = Carbon::now();
        $views = $this->views;
        $count = 0; 
        
        foreach ($views as $k => $v) {
            $vDate = Carbon::parse($v->created_at);
            if($vDate->month == $now->month)
                $count++;
        }
        
        return $count;
    }
    public function getYearviewsAttribute()
    {
        $now = Carbon::now();
        $views = $this->views;
        $count = 0; 
        
        foreach ($views as $k => $v) {
            $vDate = Carbon::parse($v->created_at);
            if($vDate->year == $now->year)
                $count++;
        }
        
        return $count;
    }

    public function getMissingvideosAttribute()
    {
        switch ($this->subscription_id) {
            case 1:
                return 4 - $this->monthviews;
                break;
            case 2:
                return 26 - $this->yearviews;
                break;
            case 3:
                return 52 - $this->yearviews;
                break;
        }
    }
    
    public function getMissingdaysAttribute()
    {
        if($this->type !== 2) return 365;

        $sale = Sale::where('user_id', $this->id)
                    ->where('status', '<>',9)
                    ->orderBy('created_at', 'DESC')
                    ->first();
        if(!$sale) return 0;
        $now = Carbon::now();
        $dateofSale = Carbon::parse($sale->created_at);
        $ddDays = $now->diffInDays($dateofSale);   


        switch ($this->subscription_id) {
            case 1:
                return $ddDays > 30 ? 0 : 30 - $ddDays;
                break;
            case 2:
                return $ddDays > 180 ? 0 : 180 - $ddDays;
                break;
            case 3:
                return 365 - $ddDays;
                break;
        }
    }
    
    public static function getSubscriptionStatus($sale, $sId){
        $now = Carbon::now();
        $dateofSale = Carbon::parse($sale->created_at);
        $ddDays = $now->diffInDays($dateofSale);   
        
        switch ($sId) {
            case 1:
                return $ddDays > 30 ? true : false;
                break;
            case 2:
                return $ddDays > 180 ? true : false;
                break;
            case 3:
                return false;
                break;
        }
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new UserResetPassword($token));
    }

}

resources/views/emailcrud/admininactiveaccount.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <img src="{{$message->embed(public_path('/assets/images/logo.png'))}}" alt="" style="max-width: 180px;height: 191px;margin-top: 14px;">
    <div  style="font-size: 22px; font-family: 'Circular Std Medium'; margin:6px;">
        Cuentas Por Suspender 
    </div>
    @foreach ($data['users'] as $i)
        <table class="table table-striped table-bordered first">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Rut</th>
                    <th>Email</th>
                    <th>Telefono</th>
                    <th>tipo de usuario</th>
                    <th>Suscripcion</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $i)
                    <tr>
                        <td>{{$i->full_name}}</td>
                        <td>{{$i->rut}}</td>
                        <td>{{$i->email}}</td>
                        <td>{{$i->phone}}</td>
                        <td>{{$i->type}}</td>
                        <td>{{$i->subscription ? $i->subscription->name:''}}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endforeach
<img src="{{$message->embed(public_path('assets/images/footer.png'))}}" / width="100%">
</body>
</html>

resources/views/emailcrud/edit.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/dataTables.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/buttons.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/select.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/fixedHeader.bootstrap4.css">
@endsection

@section('content')
    <div class="card-body">
        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif

    </div>
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="page-header">
                <h3 class="mb-2">Emails </h3>
            </div>
        </div>
    </div>
    <div class=row>
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="card-body">
                    <form action="/emails/{{$email->id}}" method="POST" enctype="multipart/form-data" >
                        @csrf
                        @method('put')
                        <input type="hidden" name="type" value="{{$email->type}}">
                        
                       
                        <div class="form-group col-md-12">
                            <label for="">Asunto</label>
                            <input class="form-control form-control-lg" type="text" name="subject" value="{{$email->subject}}" >
                        </div>
                        <div class="form-group col-md-12">
                            <label for="">Cuerpo</label>
                            <textarea  name="body" id="editor">{{$email->body}}</textarea>
                        </div>
                       <div>
                        <button class="btn  float-right" style="background-color: #8d68a9;border-color: #8d68a9; color:white">Actualizar</button>
                       </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdn.ckeditor.com/ckeditor5/17.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>
@endsection

resources/views/emailcrud/list.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/dataTables.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/buttons.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/select.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/fixedHeader.bootstrap4.css">
@endsection

@section('content')
    <div class="card-body">
        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif

    </div>
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="page-header">
                <h3 class="mb-2">Emails </h3>
            </div>
        </div>
    </div>
    <div class=row>
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered first">
                            <thead>
                                <tr>
                                    <th style="width: 40%;">Nombre</th>
                                    <th style="width: 40%;">Asunto</th>
                                    <th style="width: 10%;"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $i)
                                    <tr>
                                        <td>{{$i->type_label}}</td>
                                        <td>{{$i->subject}}</td>
                                        <td>
                                            <button data-id="{{$i->id}}" class="editB btn btn-default float-left" style="width: 60px;"><i class="fas fa-edit"></i></button>
                                           
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                           
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="/assets/vendor/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="/assets/vendor/datatables/js/buttons.bootstrap4.min.js"></script>
    <script src="/assets/vendor/datatables/js/data-table.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/rowgroup/1.0.4/js/dataTables.rowGroup.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.2.7/js/dataTables.select.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/17.0.0/classic/ckeditor.js"></script>
   
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );


        $(function(){
            $("body").on('click', '.editB', function(){
                var id = $(this).data("id")
                location.href="/emails/"+id
            })
            $("body").on('click', '.cancelEdit', function(e){
                e.preventDefault()
                location.reload()
            })
        })
    </script>
@endsection