routes/web.php
<?php

Route::get('/', function () {
    return redirect('login');
});

//Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/convenios', 'HomeController@convenios');

Route::get('/videos', 'HomeController@videos');

Route::get('/usuarios', 'HomeController@usuarios');

Route::get('/ventas', 'HomeController@ventas');

Route::get('/suscrpciones', 'HomeController@subscription');

Route::get('/subscriptionselect', 'SubscriptionController@subscriptionselect');

Route::resource('/posts','PostController');

Route::resource('/sales','SaleController');

Route::resource('/vistas','ViewsController');

Route::resource('/users','UserController');

Route::resource('/subscription','SubscriptionController');

Route::get('/userlogout', 'HomeController@logout');

Route::get('/goFlow', 'SaleController@goFlow');

Route::get('/perfil', 'HomeController@profile');

Route::get('/changeSub/{id}', 'SubscriptionController@changeSub');

Route::get('/getVideosMonth/{month}', 'PostController@getVideosMonth');

Route::post('/flowConfirm', 'SaleController@flowConfirm');

Route::post('/flowResult', 'SaleController@flowResult');


Route::get('user_list_excel', 'UserController@exportExcel')->name('users.excel');

Route::get('/user/sendmail/{id}', 'SendMailController@userShow');

Route::post('/user/mailsend/{id}', 'SendMailController@mailSend');

Route::post('/usersChangePassword/{id}', 'UserController@passchange');

Route::get('/user/newVideoMail', 'SendMailController@videoMail');

Route::get('/sendMailInactive' , 'SendMailController@sendMailInactive');

Route::get('/emails' , 'SendMailController@index');

Route::get('/emails/{id}' , 'SendMailController@edit');

Route::put('/emails/{id}' , 'SendMailController@update');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title', 'description', 'video_path', 'img_path', 'type', 'status', 'month'
    ];

    const TYPE = [
        1=>'Convenio',
        2=>'Video',
        3=>'Otro',
    ];

    const STATUS = [
        0 => 'Inactivo',
        1 => 'Activo',
    ];

    public function views()
    {
        return $this->hasMany('App\Views');
    }

    public function getStatusLabelAttribute()
    {
        return Self::STATUS[$this->status];
    }

}

resources/views/videos/add.blade.php
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel" >Agregar Video</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

            <form action="/posts" method="POST" enctype="multipart/form-data" >
                @csrf
                <input type="hidden" name="type" value="2">
                <div class="form-group col-md-12">
                    <label for="">Portada</label>
                    <input type="file" name="fileImg" class="form-control form-control-lg" placeholder="Selecciona Portada" >
                </div>
                <div class="form-group col-md-12">
                  <label for="">Video</label>
                  <input type="text" name="video_path" class="form-control form-control-lg" required=""  >
                </div>
                    
                  
                <div class="form-group col-md-12">
                    <label for="">Titulo</label>
                    <input class="form-control form-control-lg" type="text" name="title" required=""  >
                </div>
                
                <div class="form-group col-md-12">
                    <label for="">Descripcion</label>
                    <textarea  name="description" id="editor"></textarea>
                    <label for="">Este campo es obligatorio</label>
                </div>
                <div class="form-group col-md-12">
                  <label for="">Mes Correspondiente</label>
                  <input class="form-control form-control-lg" type="number" name="month" required=""  >
                </div>
                <div class="form-group col-md-12">
                    <label for="">Estado</label>
                    
                    <select name="status"  class="form-control form-control-lg" id="" required="">
                        <option value="">Selecciona</option>
                        <option value="1">Activo</option>
                        <option value="0">Inactivo</option>
                    </select>
                </div>
           

            

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-info" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-success"  style=" background-color: #8d68a9; border-color: #8d68a9; color:white">Guardar</button>
        </div>
    </form>
      </div>
    </div>
  </div>

resources/views/videos/edit.blade.php
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Editar Video</h5>
          <button type="button" class="close  cancelEdit" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form action="/posts" method="POST" enctype="multipart/form-data" >
                @csrf
                @method('put')
                <input type="hidden" name="type" value="1">
                <div class="form-group col-md-12">
                    <label for="">Portada</label>
                    <input type="file" name="fileImg" class="form-control form-control-lg" placeholder="Selecciona Portada" >
                </div>
                <div class="form-group col-md-12">
                  <label for="">Video</label>
                  <input type="text" name="video_path" class="form-control form-control-lg"  >
                </div>
                <div class="form-group col-md-12">
                    <label for="">Titulo</label>
                    <input class="form-control form-control-lg" type="text" name="title" required=""  >
                </div>
                <div class="form-group col-md-12">
                    <label for="">Descripcion</label>
                    <textarea  name="description" id="editor2"></textarea>
                </div>
                <div class="form-group col-md-12">
                  <label for="">Mes Correspondiente</label>
                  <input class="form-control form-control-lg" type="number" name="month" required=""  >
                </div>
                <div class="form-group col-md-12">
                    <label for="">Estado</label>
                    <select name="status"  class="form-control form-control-lg" id="">
                        <option value="">Selecciona</option>
                        <option value="1">Activo</option>
                        <option value="0">Inactivo</option>
                    </select>
                </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-info cancelEdit" >Cancelar</button>
          <button type="submit" class="btn btn-success">Guardar</button>
        </div>
            </form>
      </div>
    </div>
  </div>

resources/views/videos/list.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/dataTables.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/buttons.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/select.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="../assets/vendor/datatables/css/fixedHeader.bootstrap4.css">
@endsection

@section('content')
    <div class="card-body">
        @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
        @endif

    </div>
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="page-header">
                <h3 class="mb-2">Videos </h3>
            </div>
        </div>
    </div>
    <div class=row>
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <h5 class="card-header">
                    <button class="btn  float-right" data-toggle="modal" data-target="#addModal"style="
                    background-color: #8d68a9;
                    border-color: #8d68a9; color:white">Agregar</button>
                </h5>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered first">
                            <thead>
                                <tr>
                                    <th style="width: 10%;">Portada</th>
                                    <th style="width: 10%;">Video</th>
                                    <th>Titulo</th>
                                    <th>Descripcion</th>
                                    <th style="width: 10%;">Estado</th>
                                    <th style="width: 10%;"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $i)
                                    <tr>
                                        <td><img src="{{ asset("storage/$i->img_path")}}" alt="" style="max-width: 200px;"></td>
                                        <td>
                                            <video controls controlsList="nodownload" style="max-width: 200px;">
                                                <source src="{{$i->video_path}}" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' />
                                            </video>
                                        </td>
                                        <td>{{$i->title}}</td>
                                        <td>{!! substr($i->description,0,100)!!}</td>
                                        <td>{{$i->status_label}}</td>
                                        <td>
                                        <button data-id="{{$i->id}}" class="editB btn btn-default float-left" style="width: 60px;"><i class="fas fa-edit"></i></button>
                                            <form action="{{ url('/posts', ['id' => $i->id]) }}" method="post" class="float-left">
                                                <button type="submit" class="btn btn-default" style="width: 60px"><i class="far fa-trash-alt"></i></button>
                                                @method('delete')
                                                @csrf
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th style="width: 10%;">Portada</th>
                                    <th style="width: 10%;">Video</th>
                                    <th>Titulo</th>
                                    <th>Descripcion</th>
                                    <th>Estado</th>
                                    <th></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="/assets/vendor/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="/assets/vendor/datatables/js/buttons.bootstrap4.min.js"></script>
    <script src="/assets/vendor/datatables/js/data-table.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/rowgroup/1.0.4/js/dataTables.rowGroup.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.2.7/js/dataTables.select.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/17.0.0/classic/ckeditor.js"></script>
    @include('videos.add')
    @include('videos.edit')
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );


        $(function(){
          
            $("body").on('click', '.editB', function(){
                var id = $(this).data("id")
                
                $.get('/posts/'+id, function(r){
                    console.log(r)
                    $('#editModal form').attr('action', "/posts/"+r.id)
                    $('#editModal input[name=title]').val(r.title)
                    $('#editModal input[name=video_path]').val(r.video_path)
                    $('#editModal input[name=month]').val(r.month)
                    $('#editModal textarea[name=description]').text(r.description)
                    $('#editModal select[name=status]').val(r.status)
                    ClassicEditor
                        .create( document.querySelector( '#editor2' ) )
                        .catch( error => {
                            console.error( error );
                        } );
                    $('#editModal').modal()
                })
            })
            $("body").on('click', '.cancelEdit', function(e){
                e.preventDefault()
                location.reload()
            })
        })
    </script>
@endsection

resources/views/videos/videosSubido.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <img src="{{$message->embed(public_path('/assets/images/logo.png'))}}" alt="" style="max-width: 180px;height: 191px;margin-top: 14px;">
         <p style="font-size: 30px; font-family: 'Circular Std Medium';">
            <div  style="font-size: 22px; font-family: 'Circular Std Medium'; margin:6px;">
                ¡Hola! Que gusto saludarte {!!$data['user']->f_name!!}
            </div>
            {!!$data['emailData']->body!!}
        </p>
        <img src="{{$message->embed(public_path('assets/images/footer.png'))}}" / width="100%">
</body>
</html>